### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by vaskomichal** [nheijmink/livolo_homey#2]
Hi, is it possible to install this app to homey? I don't find it in-app store. 

When I try to install I got this error

rror: Cannot find module '../DefaultDevice'
Require stack:
- /lib/devices/livolo/livolo.js
- /lib/devices/livolo/remote.js
- /lib/devices/livolo/wall_switch.js
- /drivers/C701R/device.js
- /node_modules/homey-rfdriver/lib/Driver.js
- /node_modules/homey-rfdriver/index.js
- /drivers/C701R/driver.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:191)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/lib/devices/livolo/livolo.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/lib/devices/livolo/livolo.js',
    '/lib/devices/livolo/remote.js',
    '/lib/devices/livolo/wall_switch.js',
    '/drivers/C701R/device.js',
    '/node_modules/homey-rfdriver/lib/Driver.js',
    '/node_modules/homey-rfdriver/index.js',
    '/drivers/C701R/driver.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js'
  ]
}

**Comment by iWelna** [comment]
I sold all my livolos and bought a other Wifi ones, even with zigbee2mqtt switches i had problems with it.  Ofcourse You could use broadlink and RF ones, but without proper status U cant make nice flows 👍

**Comment by vaskomichal** [comment]
> I sold all my livolos and bought a other Wifi ones, even with zigbee2mqtt switches i had problems with it. Ofcourse You could use broadlink and RF ones, but without proper status U cant make nice flows 👍

Hi, Thank you for your response. I have an EU version without RF only with zigbee than broadlink is not possible to use. 
If I send you donations is it possible to fix the problem? I understand you no longer have a livolo device but now the problem is that livolo app doesn't run on Homey. Is it possible to fix it that app is possible to build it and run it correctly with Homey? 
Then  I test the functionality with the livolo switch. So you don't really need it. Thakns!
